version: '2'
services:
  web:
    #image: docker.io/tobru/odoo-pos:latest-pos
    image: docker.io/library/odoo:15
    #build: ./odoo
    depends_on:
      - db
    ports:
      - 80:8069
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
